name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  SonarCloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=Anusha_codtech-task-4
            -Dsonar.organization=azhw_l9v3znbxy2g1sar
            -Dsonar.python.version=3.8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
